name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: |
          cd src
          go mod download

      - name: Run unit tests
        run: |
          cd src
          go test -coverprofile=coverage.txt ./internal/...

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./src/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
